"use client";

import { formatDuration } from "@/lib/format";
import type { Rundown, ShowState } from "@/lib/types";

/**
 * The pre-show. Whenever nothing is on air — the model is still building the
 * opening (`loading`), the projector is warming up, it has lost the model, or
 * it is not running at all — this covers the player edge to edge, so a viewer
 * never sees the black frames the stream carries meanwhile.
 *
 * It is drawn entirely on this side. Nothing here is generated by the model;
 * the model's first frame is the first frame anyone sees, and only once the
 * projector has buffered enough of the screening that playout cannot outrun
 * the builds behind it. The curtain shows that buffer filling as a film-leader
 * ring counting down, and the programme for the screening about to start.
 *
 * Layout is governed by container queries on the player's box (`.curtain-*`
 * rules in globals.css): the title and ring scale with the box height, and
 * the kicker, tagline, buffer readout, and programme are dropped one by one
 * as the box gets shorter, so nothing ever overflows or overlaps — the same
 * markup fits a phone and a wall.
 */

type Mode = "loading" | "warming" | "downtime" | "offair";

export function Curtain({
  state,
  rundown,
  offAir,
}: {
  state: ShowState | null;
  rundown: Rundown | null;
  offAir: boolean;
}) {
  const mode: Mode = offAir
    ? "offair"
    : state?.status === "loading"
      ? "loading"
      : state?.status === "downtime"
        ? "downtime"
        : "warming";

  const programme =
    rundown && (mode !== "loading" || rundown.screening === state?.screening) ? rundown : null;
  const title =
    (mode === "loading" && state?.episode_title) || programme?.episodes[0]?.title || "OpenSlop";

  const buffered = state?.buffered_seconds ?? 0;
  const target = state?.target_seconds ?? 0;
  const ratio = mode === "loading" && target > 0 ? Math.min(1, buffered / target) : null;
  const secondsLeft = ratio === null ? null : Math.max(0, Math.ceil(target - buffered));

  const statusLine = {
    loading: "preparing the reels",
    warming: "warming up the projector",
    downtime: "reconnecting the projector",
    offair: "the projector is not running",
  }[mode];

  return (
    <div className="curtain curtain-pad absolute inset-0 flex flex-col items-center justify-between overflow-hidden bg-[#050505] text-zinc-200">
      <div className="curtain-grain pointer-events-none absolute inset-0 opacity-[0.07]" />
      <div className="curtain-vignette pointer-events-none absolute inset-0" />

      <header className="relative flex min-w-0 max-w-full flex-col items-center gap-1 text-center">
        <span className="curtain-kicker items-center gap-2 font-mono text-[10px] uppercase tracking-[0.35em] text-zinc-500">
          OpenSlop
          {typeof state?.screening === "number" && mode !== "offair" && (
            <> · screening nº {state.screening}</>
          )}
        </span>
        <h2 className="curtain-title curtain-rise max-w-full truncate px-2 font-light tracking-tight text-zinc-50">
          {mode === "offair" ? "Off air" : title}
        </h2>
        <p className="curtain-tagline curtain-rise-late max-w-[84ch] text-balance font-mono text-[11px] leading-relaxed text-zinc-500">
          <Tagline mode={mode} state={state} programme={programme} />
        </p>
      </header>

      <div className="relative flex flex-col items-center gap-2">
        <Leader ratio={ratio} secondsLeft={secondsLeft} mode={mode} />
        <span className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.3em] text-zinc-500">
          <span className="curtain-blink inline-block h-1.5 w-1.5 rounded-full bg-accent" />
          {statusLine}
        </span>
      </div>

      <footer className="relative flex w-full flex-col items-center gap-3">
        {programme && programme.episodes.length > 0 && <Programme rundown={programme} />}
        {mode === "loading" && (
          <div className="curtain-buffer w-full max-w-sm">
            <div className="h-px w-full bg-white/10">
              <div
                className="h-px bg-accent transition-[width] duration-1000 ease-linear"
                style={{ width: `${(ratio ?? 0) * 100}%` }}
              />
            </div>
            <div className="mt-1.5 flex justify-between font-mono text-[10px] text-zinc-600">
              <span>{Math.floor(buffered)}s built</span>
              <span>of {Math.ceil(target)}s</span>
            </div>
          </div>
        )}
      </footer>
    </div>
  );
}

function Tagline({
  mode,
  state,
  programme,
}: {
  mode: Mode;
  state: ShowState | null;
  programme: Rundown | null;
}) {
  if (mode === "offair") {
    return <>nobody is projecting right now — the screenplay is still open on GitHub</>;
  }
  if (mode === "downtime") {
    return <>we lost the model for a moment · this screening starts over from the top</>;
  }
  if (mode === "warming") {
    return <>{state?.detail || "reading the story…"}</>;
  }
  const scenes =
    state?.scene_total ??
    programme?.episodes.reduce((count, episode) => count + episode.scenes.length, 0) ??
    0;
  const seconds = state?.film_seconds ?? programme?.total_seconds;
  return (
    <>
      {state?.restart && <>starting over from the top · </>}the first ever open source movie
      {scenes > 0 && (
        <>
          {" "}
          · {scenes} scene{scenes === 1 ? "" : "s"}
        </>
      )}
      {typeof seconds === "number" && seconds > 0 && <> · {formatDuration(seconds)}</>}
      {state?.sha && (
        <>
          {" "}
          · story at <span className="text-zinc-400">{state.sha}</span>
        </>
      )}
    </>
  );
}

/**
 * A film-leader ring. While loading, the arc fills with the buffer and the
 * number counts the seconds of film still to build. Warming or reconnecting,
 * the arc turns on its own, saying only that time is passing. Off air it is a
 * still, empty ring.
 */
function Leader({
  ratio,
  secondsLeft,
  mode,
}: {
  ratio: number | null;
  secondsLeft: number | null;
  mode: Mode;
}) {
  const radius = 44;
  const circumference = 2 * Math.PI * radius;
  const idle = ratio === null;
  const filled = idle ? circumference * (mode === "offair" ? 0 : 0.22) : circumference * ratio;
  return (
    <div className="curtain-ring relative">
      <svg viewBox="0 0 100 100" className="h-full w-full">
        <circle cx="50" cy="50" r={radius} fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth="1" />
        <circle
          cx="50"
          cy="50"
          r={radius}
          fill="none"
          stroke="var(--color-accent)"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeDasharray={`${filled} ${circumference}`}
          transform="rotate(-90 50 50)"
          className={
            idle && mode !== "offair"
              ? "curtain-spin origin-center"
              : "transition-[stroke-dasharray] duration-1000 ease-linear"
          }
        />
        {/* the leader's crosshair */}
        <line x1="50" y1="2" x2="50" y2="10" stroke="rgba(255,255,255,0.18)" strokeWidth="0.75" />
        <line x1="50" y1="90" x2="50" y2="98" stroke="rgba(255,255,255,0.18)" strokeWidth="0.75" />
        <line x1="2" y1="50" x2="10" y2="50" stroke="rgba(255,255,255,0.18)" strokeWidth="0.75" />
        <line x1="90" y1="50" x2="98" y2="50" stroke="rgba(255,255,255,0.18)" strokeWidth="0.75" />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        {secondsLeft !== null ? (
          <span
            key={secondsLeft}
            className="curtain-ring-number curtain-tick font-mono font-light leading-none tabular-nums text-zinc-50"
            title="seconds of movie still to build"
          >
            {secondsLeft}
          </span>
        ) : (
          <span className="font-mono text-[10px] uppercase tracking-[0.3em] text-zinc-500">
            {mode === "offair" ? "—" : "…"}
          </span>
        )}
      </div>
    </div>
  );
}

const PROGRAMME_LIMIT = 4;

function Programme({ rundown }: { rundown: Rundown }) {
  const shown = rundown.episodes.slice(0, PROGRAMME_LIMIT);
  const rest = rundown.episodes.length - shown.length;
  return (
    <ol className="curtain-programme max-w-3xl flex-wrap items-baseline justify-center gap-x-4 gap-y-1 font-mono text-[11px] text-zinc-500">
      {shown.map((episode, index) => (
        <li key={episode.file} className="flex max-w-[16rem] items-baseline gap-1.5">
          <span className="text-zinc-700">{String(index + 1).padStart(2, "0")}</span>
          <span className="truncate text-zinc-300">{episode.title || episode.file}</span>
          <span className="text-zinc-600">{formatDuration(episode.seconds)}</span>
        </li>
      ))}
      {rest > 0 && <li className="text-zinc-600">+{rest} more</li>}
    </ol>
  );
}
